application: cloud-data-api
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /_ah/spi/.*
  script: cloud_data.api
  secure: always

libraries:
- name: endpoints
  version: 1.0

skip_files:
- ^(.*/)?.*\.py[co]$ # skip compiled .pyc/.pyo files
- ^(.*/)?\..*$ # skip .git, .gitignore, any_folder/.DS_Store...
- ^README\..*
- ^LICENSE
